

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../componets/header/HeaderWrapper";
import Main from "../../componets/main/Main";
import About from "../../componets/about/About";
import Skills from "../../componets/Skills/Skills";
import Portfolio from "../../componets/portfolio/Portfolio";
import Contact from "../../componets/contact/Contact";
import Footer from "../../componets/footer/Footer";

// import { color } from "framer-motion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="icon"
          type="image/svg+xml"
          sizes="52x52"
          href="/logo/logo.svg"
        />
      </head>
      <body>
        <Header />
        <Main />
        <About />
        <Skills />
        <Portfolio />
        <Contact />
        <Footer />
        {children}
      </body>
    </html>
  );
}
